export const UPDATE_RESULTS = 'UPDATE_RESULTS';

export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';

export const UPDATE_SEARCH_LOCATION = 'UPDATE_SEARCH_LOCATION';

export const UPDATE_SEARCH_RADIUS = 'UPDATE_SEARCH_RADIUS';